basket/urls.py
from django.urls import include, path

from . import views

app_name ='basket'

urlpatterns = [
            path('',views.basket_summary,name='basket_summary'),
            path('add/',views.basket_add,name='basket_add'),
            path('delete/',views.basket_delete,name='basket_delete'),
            path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

from store import urls
from basket import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('store/',include('store.urls',namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import include, path

from . import views

app_name ='store'

urlpatterns = [
    
    path('',views.products_all,name='products_all' ),
    path('<slug:slug>',views.product_detail,name='product_detail'),
    path('shop/<slug:category_slug>/',views.category_list,name='category_list')

]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.




class Category(models.Model):
    name = models.CharField(max_length=256)
    slug =models.SlugField(max_length=255)
    description =models.CharField(max_length=255,blank=True)
    cat_img =models.ImageField(upload_to='category_images/',blank=True)
    is_active =models.BooleanField(default=True)

    
    class Meta:

        verbose_name_plural ='Categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):

        return self.name
    
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class ProductStockManager(models.Manager):
    def get_queryset(self):
        return super(ProductStockManager, self).get_queryset().filter(in_stock=False)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()
    not_in_stock = ProductStockManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render,get_object_or_404
from django.http import JsonResponse

from .basket import Basket
from store.models import Product

# Create your views here.

def basket_summary(request):
   basket =Basket(request)
   
   return render(request,'store/basket/summary.html',{'basket':basket})


   
def basket_add(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        print(request.session['skey'])
       # print(request.session.keys())
        
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product,qty=product_qty)
        basket_qty=basket.__len__()
        
        response = JsonResponse({'qty':basket_qty})
        print(response)
        return response
    


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

core/views.py
from django.shortcuts import  render
from store.models import Product


def index(request):

    products = Product.products.all()

    return  render(request,'core/index.html',{'products': products[2:]})

store/views.py
from django.shortcuts import render,get_object_or_404

from .models import Category,Product

# Create your views here.

def categories(request):
    categories = Category.objects.all()
    return {
        'categories': categories
    }


def products_all(request):

    products = Product.products.all()
    

    return render(request, 'store/store.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    print(product)
    return render(request, 'store/products/sin.html', {'product': product})


def category_list(request, category_slug):

    category = get_object_or_404(Category, slug=category_slug)
    print(category)
    products = Product.products.filter(category=category)
    print(products)

    return render(request, 'store/products/categroy.html', {'category': category, 'products': products})

templates/base/shoes_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}E-Store{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Chilanka&family=Montserrat:wght@300;400;500&display=swap"
  rel="stylesheet">

    <link href= "{% static 'css/main.css' %}" rel="stylesheet">


<style>

    :root {
        --accent-color: #DEAD6F;
        --dark-color: #222222;
        --light-dark-color: #727272;
        --light-color: #fff;
        --grey-color: #dbdbdb;
        --light-grey-color: #fafafa;
        --primary-color: #6995B1;
        --light-primary-color: #eef1f3;
      }
      

      :root {
        --body-font: 'Chilanka', cursive;
        --heading-font: 'Chilanka', cursive;
        --secondary-font: 'Montserrat', sans-serif;
      }

      body{
        font-family:'Montserrat', sans-serif;
         /*background:#CBBEB3;*/
         
      }
      .n {
       
        background:#FFFAFF;

      }
      .n a{
      
      }
      footer{
        background:#FC5130;
        
      }
 

      

</style>
{% comment %} font-family:'Chilanka', cursive  {% endcomment %}
    
   
</head>

<body>


      
    <header class="">

        <nav class=" n navbar navbar-expand-md  border-bottom ">
            <div class=" container-fluid ">
                <a class="navbar-brand" href="#">E-Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul id ="#mycat" class=" navbar-nav mx-auto mb-2 mb-md-0  pt-2">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                               Store
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'store:products_all'  %}">All</a></li>
                               
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{c.get_absolute_url}}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %} 
                            
                            </ul>
                        </li>
                    </ul>
                    <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                        class="btn btn-outline-secondary">
                        

                         {% with totalqty=basket|length %} 
                        <div id="basket-qty" class="d-inline-flex">
                        {% if totalqty > 0 %}
                        {{totalqty}}
                        
                        {% else %}
                            0
                        {% endif %} 
                    </div>
                      {% endwith %} 
                           

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Basket
                    </a>
                    {% comment %} <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
               {% endcomment %}
            </div> 
            </div>
    
       
    
    
    
    
    </header>

    <div id="content">{% block content %} {% endblock %}</div>

    <div>

      <footer class=" container-fluid py-4 my-5">
        <div class="row">
          <div class="col-12 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
            <small class="d-block mb-3 text-body-secondary">&copy;NomadCoder 2017–2024</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="  list-unstyled text-small">
              <li><a class="link-secondary text-black text-decoration-none" href="#">Cool stuff</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Random feature</a></li>
              <li><a class="link-secondary text-black  text-decoration-none" href="#">Team feature</a></li>
              <li><a class="link-secondary text-black  text-decoration-none" href="#">Stuff for developers</a></li>
              <li><a class="link-secondary text-black  text-decoration-none" href="#">Another one</a></li>
              <li><a class="link-secondary text-black  text-decoration-none" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="link-secondary text-black text-decoration-none" href="#">Resource name</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Resource</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Another resource</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="link-secondary text-black text-decoration-none" href="#">Business</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Education</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Government</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Gaming</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="link-secondary text-black text-decoration-none" href="#">Team</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Locations</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Privacy</a></li>
              <li><a class="link-secondary text-black text-decoration-none" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    
    
    </div>

    {% block footer %}

{% endblock footer %}    


</body>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> <!--responsive nav didnt work without it-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.15/jsrender.min.js" integrity="sha512-6heofwTnm0osmeEuz47jQLMVpAe2/ww+hZ4xvyv/kgedYO0b9mhNnsh8nUQZrmcdbaDkxrN+1K4SV6L+V4EH6Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
</html>
        

templates/store/basket/summary.html
{% extends "../../base/shoes_base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %} 
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block m-4" width="140px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Price</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">£{{ item.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %} 
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: £<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
    </div>
  </div>
</main>



<script>
   // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        console.log(prodid)
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })


  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}

templates/store/includes/card.html
<div class="card p-2 ">
    <div> <img src="{{product.image.url}}" alt="Nike" style="width:100%">

     </div>
     <div>
     <h1 class="p-3">{{product.title|title}}</h1>
     <p class="price">${{product.price}}</p>
     <p>{{product.description}}</p>
     <p><button>Add to Cart</button></p>
   </div> 
 </div>

templates/store/products/categroy.html
{% extends "../../base/shoes_base.html" %} {% load static %}

<title>
  {% block title %}{% if category %}{{category.name}} {% else %} Products {%endif %}{% endblock %}
</title>

{% block content %}

<style>

  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    font-family: arial;
  }
  
  .card:hover{
    box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.8);
  }

  .price {
    color: grey;
    font-size: 22px;
  }
  
  .card button {
    border: none;
    outline: 0;
    padding: 12px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
  }
  
  .card button:hover {
    opacity: 0.7;
  }

.bc{

  background:#FC5130;
  
}





</style>

<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in products %}
        <div class="card p-2 ">
          <div> <a href="{{ product.get_absolute_url }}"><img src="{{product.image.url}}" alt="Nike" style="width:100%"></a>
      
           </div>
           <div>
           <h1 class="p-3">{{product.title|title}}</h1>
           <p class="price">${{product.price}}</p>
           <p>{{product.description}}</p>
           <p><a href="{{ product.get_absolute_url }}"><button>Learn More</button></a></p>
         </div> 
       </div>
       
        {% endfor %}
      </div>
    </div>
  </div>
</main>

{% endblock content %}

templates/store/products/single.html
{% extends "../../base/shoes_base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="400px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Brand)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
<button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

 <script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        //console.log($('#select option:selected').text())
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
              document.getElementById("basket-qty").innerHTML = json.qty
              console.log(json)
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script> 

{% endblock %}

templates/store/store.html
{% extends "../base/shoes_base.html" %}
{% load static %}

{% block title %}
Store
{% endblock title %}

{% block content %}

<style>

  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    font-family: arial;
  }

  .card:hover{
    box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.8);
  }
  
  .price {
    color: grey;
    font-size: 22px;
  }
  
  .card button {
    border: none;
    outline: 0;
    padding: 12px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
  }
  
  .card button:hover {
    opacity: 0.7;
  }


</style>






<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-4 h1">Shop</div>
   
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3  g-3">
        {% for product in products %}

        <div class="card p-2 m-3 mx-auto">
         <div> <a href="{{ product.get_absolute_url }}" ><img src="{{product.image.url}}" alt="Nike" style="width:100%"></a>

          </div>
          <div>
          <h1 class="p-3">{{product.title|title}}</h1>
          <p class="price">${{product.price}}</p>
          <p>{{product.description}}</p>
         
          <p><a href="{{ product.get_absolute_url }}"><button>Learn More</button></a></p>
          
        </div> 
      </div>
     {% endfor %}
      </div>
    </div>
  </div>
</main>


<script>


  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    //console.log($('#select option:selected').text())
    $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_add" %}',
        data: {
            productid: $('#add-button').val(),
            productqty: $('#select option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.qty
          console.log(json)
        },
        error: function (xhr, errmsg, err) {}
    });
})
</script> 

{% endblock content %}

{% block footer %}



{% endblock footer %}